# random Module

## random method
Returns a random float
## uniform method
Returns a random float within specified range
## randint method
Returns a random integer within a specified range (including the upperbound)
## randrange method
Returns a random integer within a specified range (excluding the upperbound)
## normalvariate method
Returns a random normal distribution value of a specified mean (mu) & std. deviation (sigma)

In [ ]:
import random as r

a = r.random()
print(a)                                                         # 0.909374908539443

a = r.uniform(0, 10)
print(a)                                                         # 2.3912342329981486

a = r.randint(0, 10)
print(a)                                                         # 10

a = r.randrange(0, 10)
print(a)                                                         # 6

a = r.normalvariate(0, 1)
print(a)                                                         # 0.07991091682502621

## List operations
## choice method
Returns a random element from a given list
## sample method
Returns unique random element combination list (no. of required elements should be specified) from a given list (never picks an element twice)
## choices method
Returns random element combination list (k = no. of required elements, should be specified) from a given list
## shuffle method
Returns a randomly shuffled list from a given list

In [ ]:
l = list("MYNAMEISSAYAN")

a = r.choice(l)
print(a)                                                        # M

a = r.sample(l, 3)
print(a)                                                        # ['N', 'M', 'N']

a = r.choices(l, k=3)
print(a)                                                        # ['E', 'E', 'Y']

r.shuffle(l)
print(l)                                                        # ['A', 'I', 'A', 'Y', 'E', 'N', 'S', 'M', 'M', 'Y', 'S', 'A', 'N']

## seed method
random module returns pseudorandom numbers, which are reproducable. Using seed method we can verify that. Same seed value always returns same random values.

In [ ]:
r.seed(1)
print(r.random())                                              # 0.13436424411240122
print(r.randint(1,10))                                         # 2

r.seed(2)
print(r.random())                                              # 0.9560342718892494
print(r.randint(1,10))                                         # 1

r.seed(1)
print(r.random())                                              # 0.13436424411240122
print(r.randint(1,10))                                         # 2

r.seed(2)
print(r.random())                                              # 0.9560342718892494
print(r.randint(1,10))                                         # 1

# secrets module
To overcome the reproducibility of random module, we can use secrets module instead. It returns truly random numbers.

## randbelow method
Returns a random integer within 0 and the specified upperbound (excluding the upperbound)
## randbits method
Returns a number made out of random bits (0 or 1) of specified bit length
## choice method
Returns a truly random element from a given list

In [ ]:
import secrets as s

a = s.randbelow(10)
print(a)                                                        # 9

a = s.randbits(16)
print(a)                                                        # 8217 (random 16 bit number)

l = list("MYNAMEISSAYAN")
a = r.choice(l)
print(a)                                                        # Y


## numpy module
Can be used to produce arrays consisting random numbers. It also has seed generator but different from random module's.

## random.rand method
Returns an array of specified size consisting random floats
## random.randint method
Returns an array of specified size consisting random integers within specified range
## random.shuffle method
Shuffles the rows of given array

In [ ]:
import numpy as np
import numpy.random as nr

a = nr.rand(3)
print(a)                                                       # [0.23245331 0.7128889  0.61853624]

a = nr.rand(3,4)
print(a)                                                       # [[0.77228585 0.03977584 0.9912012  0.57532302]
                                                               #  [0.41700077 0.5322194  0.69526676 0.92317468]
                                                               #  [0.56456138 0.46168652 0.73763958 0.86822372]]

a = nr.randint(0, 10, 3)
print(a)                                                       # [4 1 0]

a = nr.randint(0, 10, (3,4))
print(a)                                                       # [[0 2 9 0]
                                                               #  [5 9 5 3]
                                                               #  [3 6 1 0]]

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)                                                     # [[1 2 3]
                                                               #  [4 5 6]
                                                               #  [7 8 9]]
nr.shuffle(arr)
print(arr)                                                     # [[4 5 6]
                                                               #  [7 8 9]
                                                               #  [1 2 3]]